CREATE TABLE `company_standard_configs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`org_unit_id` integer,
	`standard_id` integer NOT NULL,
	`adoption_status` text DEFAULT 'planning',
	`first_adoption_year` integer,
	`target_compliance_year` integer,
	`compliance_rate` real DEFAULT 0,
	`responsible_user_id` integer,
	`config` text,
	`notes` text,
	`is_primary` integer DEFAULT false,
	`enabled` integer DEFAULT true,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`org_unit_id`) REFERENCES `org_units`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`standard_id`) REFERENCES `esg_standards`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`responsible_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `disclosure_requirements` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`standard_id` integer NOT NULL,
	`code` text NOT NULL,
	`title` text NOT NULL,
	`title_en` text,
	`description` text,
	`description_en` text,
	`disclosure_level` text DEFAULT 'mandatory' NOT NULL,
	`applicability_conditions` text,
	`applicable_industries` text,
	`reporting_location` text,
	`format_requirements` text,
	`deadline_rule` text,
	`non_compliance_consequences` text,
	`exemptions` text,
	`transition_provisions` text,
	`related_metric_ids` text,
	`priority` integer DEFAULT 100,
	`sort_order` integer DEFAULT 0,
	`enabled` integer DEFAULT true,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`standard_id`) REFERENCES `esg_standards`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `esg_standards` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`code` text NOT NULL,
	`name` text NOT NULL,
	`name_en` text,
	`issuer` text NOT NULL,
	`applicable_regions` text NOT NULL,
	`standard_type` text NOT NULL,
	`version` text,
	`effective_date` text,
	`next_revision_date` text,
	`status` text DEFAULT 'active' NOT NULL,
	`description` text,
	`official_url` text,
	`config` text,
	`sort_order` integer DEFAULT 0,
	`enabled` integer DEFAULT true,
	`created_at` integer,
	`updated_at` integer
);
--> statement-breakpoint
CREATE UNIQUE INDEX `esg_standards_code_unique` ON `esg_standards` (`code`);--> statement-breakpoint
CREATE TABLE `metric_mappings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`local_metric_id` integer NOT NULL,
	`standard_metric_id` integer NOT NULL,
	`mapping_type` text DEFAULT 'exact' NOT NULL,
	`confidence` integer DEFAULT 100,
	`transformation_notes` text,
	`transformation_formula` text,
	`unit_conversion_factor` real,
	`data_difference_notes` text,
	`requires_additional_data` integer DEFAULT false,
	`additional_data_notes` text,
	`is_auto_mapped` integer DEFAULT false,
	`is_verified` integer DEFAULT false,
	`verified_by` integer,
	`verified_at` integer,
	`enabled` integer DEFAULT true,
	`created_by` integer,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`local_metric_id`) REFERENCES `esg_metrics`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`standard_metric_id`) REFERENCES `standard_metrics`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`verified_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `standard_compliance_tracking` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_standard_config_id` integer NOT NULL,
	`standard_metric_id` integer NOT NULL,
	`period` text NOT NULL,
	`status` text DEFAULT 'not_started',
	`completion_rate` integer DEFAULT 0,
	`local_record_ids` text,
	`disclosure_summary` text,
	`data_quality` text,
	`is_verified` integer DEFAULT false,
	`verified_by` integer,
	`verified_at` integer,
	`notes` text,
	`exemption_reason` text,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`company_standard_config_id`) REFERENCES `company_standard_configs`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`standard_metric_id`) REFERENCES `standard_metrics`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`verified_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `standard_metrics` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`standard_id` integer NOT NULL,
	`topic_id` integer,
	`code` text NOT NULL,
	`name` text NOT NULL,
	`name_en` text,
	`description` text,
	`description_en` text,
	`disclosure_level` text DEFAULT 'mandatory',
	`data_type` text DEFAULT 'quantitative',
	`unit` text,
	`frequency` text DEFAULT 'annual',
	`calculation_guidance` text,
	`references` text,
	`cross_references` text,
	`assurance_required` integer DEFAULT false,
	`sort_order` integer DEFAULT 0,
	`enabled` integer DEFAULT true,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`standard_id`) REFERENCES `esg_standards`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`topic_id`) REFERENCES `standard_topics`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `standard_topics` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`standard_id` integer NOT NULL,
	`parent_id` integer,
	`code` text NOT NULL,
	`name` text NOT NULL,
	`name_en` text,
	`topic_type` text DEFAULT 'topic',
	`dimension` text,
	`description` text,
	`sort_order` integer DEFAULT 0,
	`created_at` integer,
	FOREIGN KEY (`standard_id`) REFERENCES `esg_standards`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `standard_update_logs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`standard_id` integer NOT NULL,
	`update_type` text NOT NULL,
	`update_date` text NOT NULL,
	`previous_version` text,
	`new_version` text,
	`change_summary` text,
	`change_details` text,
	`impact_assessment` text,
	`transition_deadline` text,
	`source_url` text,
	`created_at` integer,
	FOREIGN KEY (`standard_id`) REFERENCES `esg_standards`(`id`) ON UPDATE no action ON DELETE cascade
);
